name: Machine Learning Workflow CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-train:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Check Env
      run: |
        echo "Memeriksa ketersediaan kredensial rahasia..."
        if [ -z "${{ secrets.DAGSHUB_TOKEN }}" ]; then echo "WARNING: DAGSHUB_TOKEN kosong"; fi
        if [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then echo "WARNING: DOCKERHUB_TOKEN kosong"; fi

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow dagshub scikit-learn pandas numpy matplotlib seaborn

    - name: Run mlflow project
      env:
        DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
        DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        DAGSHUB_REPO_NAME: "predictive-maintenance-mlflow"
      run: |
        # Menggunakan GIT_DIR=/dev/null memaksa MLflow mengabaikan deteksi Git repository agar tidak error 128
        GIT_DIR=/dev/null mlflow run ./MLProject --env-manager local --experiment-name "Predictive_Maintenance_CI"

    - name: Upload to GitHub Artifacts (Skilled Target)
      uses: actions/upload-artifact@v4
      with:
        name: model-artifacts
        path: |
          CI_Classification_Report.txt
          CI_Confusion_Matrix.png

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker Image (Advanced Target)
      run: |
        # Membangun docker image menggunakan model lokal hasil tracking
        mlflow models build-docker -m "mlruns/0/$(ls mlruns/0/ | grep -v 'meta.yaml' | head -n 1)/artifacts/model" -n "${{ secrets.DOCKERHUB_USERNAME }}/predictive-maintenance-model:latest" --env-manager local

    - name: Push Docker Image
      run: |
        docker push "${{ secrets.DOCKERHUB_USERNAME }}/predictive-maintenance-model:latest"
