name: Machine Learning Workflow CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-train:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow==2.11.3 dagshub scikit-learn pandas numpy matplotlib seaborn

    - name: Run modelling script
      env:
        DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
        DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        DAGSHUB_REPO_NAME: "predictive-maintenance-mlflow"
      run: |
        # Kita jalankan langsung python-nya untuk menghindari bug 'mlflow run' di GitHub Actions
        python MLProject/modelling.py

    - name: Upload to GitHub Artifacts (Skilled Target)
      uses: actions/upload-artifact@v4
      with:
        name: model-artifacts
        path: |
          CI_Classification_Report.txt
          CI_Confusion_Matrix.png

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker Image (Advanced Target)
      run: |
        # Membangun Docker Image langsung dari model lokal hasil training yang tercatat di mlruns
        mlflow models build-docker -m "mlruns/0/$(ls mlruns/0/ | grep -v 'meta.yaml' | head -n 1)/artifacts/model" -n "${{ secrets.DOCKERHUB_USERNAME }}/predictive-maintenance-model:latest" --env-manager local

    - name: Push Docker Image
      run: |
        docker push "${{ secrets.DOCKERHUB_USERNAME }}/predictive-maintenance-model:latest"
